# Generated by Django 4.1.5 on 2023-01-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
