# Generated by Django 4.1.5 on 2023-01-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_profile_location_alter_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
