# Generated by Django 4.1.5 on 2023-01-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_alter_skill_name_alter_skill_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
