# Generated by Django 4.1.5 on 2023-02-01 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_remove_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('email', models.EmailField(max_length=200, null=True)),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_users.profile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.profile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('created', 'subject'),
            },
        ),
    ]
