# Generated by Django 4.1.5 on 2023-02-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0013_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
