# Generated by Django 4.1.5 on 2023-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='projects/project-default.jpg', upload_to='projects/'),
        ),
    ]
