# Generated by Django 4.1.5 on 2023-01-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_project_demo_link_alter_project_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app_main.tag'),
        ),
    ]
